module.exports = {
    1:{
        title:'职员列表',
        to:'/home/staff',
        class:'职员管理'
    },
    2:{
        title:'添加职员',
        to:'/home/staffadd',
        class:'职员管理'
    },
    3:{
        title:'用户列表',
        to:'/home/user',
        class:'用户管理'
    },
    4:{
        title:'意向列表',
        to:'/home/amzinglist',
        class:'客服管理'
    },
    5:{
        title:'联系我们',
        to:'/home/contact',
        class:'客服管理'
    },
    6:{
        title:'角色列表',
        to:'/home/rolelist',
        class:'系统管理'
    },
    7:{
        title:'添加角色',
        to:'/home/roleadd',
        class:'系统管理'
    },
    8:{
        title:'产品列表',
        to:'/home/productlist',
        class:'产品管理'
    },
    9:{
        title:'添加产品',
        to:'/home/productadd',
        class:'产品管理'
    },
    10:{
        title:'游记列表',
        to:'/home/booklist',
        class:'游记管理'
    },
    11:{
        title:'添加游记',
        to:'/home/bookadd',
        class:'游记管理'
    }
}